sonar.projectKey=cohort-9-mern-14307-arfa
sonar.projectName=10Pearls Shine Notes App - Arfa Riaz
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src,frontend/src
sonar.tests=backend/test,frontend/src/test
sonar.test.inclusions=backend/test/**/*.ts,frontend/src/test/**/*.ts,frontend/src/test/**/*.tsx

sonar.exclusions=frontend/src/test/**
sonar.typescript.tsconfigPaths=backend/tsconfig.test.json,frontend/tsconfig.app.json,frontend/tsconfig.test.json
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.coverage.exclusions=backend/src/server.ts,backend/src/types/**,frontend/src/main.tsx
